Q1

In [22]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'name': ['Tom', 'Jerry', 'Mike'],
                   'score': [85, 92, 78],
                   'gender': ['男', '女', '男']})
df1

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [23]:
df1.head(1)

  name  score gender
0  Tom     85      男

In [24]:
df1.shape

(3, 3)

In [25]:
df1.dtypes

name        str
score     int64
gender      str
dtype: object

In [26]:
data = [[1, "A"], [2, "B"], [3, "C"]]
df2 = pd.DataFrame(data, columns=['id', 'tag'])

df2

   id tag
0   1   A
1   2   B
2   3   C

Q2

In [27]:
df1[['score', 'gender']]

   score gender
0     85      男
1     92      女
2     78      男

In [28]:
df1.iloc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [29]:
df1[df1['score'] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [30]:
df1['grade'] = np.where(df1['score'] >= 90, '优秀', '良好')
df1

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

Q3

In [31]:
df3 = pd.DataFrame({"x": [1, None, 3], "y": [None, 5, 6]})
df3

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [32]:
df3.isnull()

       x      y
0  False   True
1   True  False
2  False  False

In [33]:
df3.isnull().sum()

x    1
y    1
dtype: int64

In [34]:
df3.fillna(0)

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

In [35]:
df3.dropna()

     x    y
2  3.0  6.0

Q4

In [36]:
df_group_score = df1.groupby("gender")["score"].agg(["mean", "max"])
df_group_score.columns = ["分数均值", "分数最大值"]
df_group_score

        分数均值  分数最大值
gender
女       92.0     92
男       81.5     85

In [37]:
df_group_count = df1.groupby("gender").size().reset_index(name="人数")
df_group_count

  gender  人数
0      女   1
1      男   2

Q5

In [38]:
df_sort_asc = df1.sort_values("score", ascending=True)
df_sort_asc

    name  score gender grade
2   Mike     78      男    良好
0    Tom     85      男    良好
1  Jerry     92      女    优秀

In [39]:
df_with_dup = pd.concat([
    df1, 
    pd.DataFrame({"name": ["Tom"], "score": [85], "gender": ["男"], "grade": ["良好"]})
], ignore_index=True)
df_with_dup

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好
3    Tom     85      男    良好

In [40]:
df_unique = df_with_dup.drop_duplicates()
df_unique

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

Q6

In [41]:
df1_merge = pd.DataFrame({"id": [1, 2], "name": ["X", "Y"]})
df2_merge = pd.DataFrame({"id": [1, 2], "age": [20, 30]})
df_merged = pd.merge(df1_merge, df2_merge, on="id")
df_merged

   id name  age
0   1    X   20
1   2    Y   30

In [42]:
df_a = pd.DataFrame({"val": [1, 2]})
df_b = pd.DataFrame({"val": [3, 4]})
df_concat = pd.concat([df_a, df_b], ignore_index=True)
df_concat

   val
0    1
1    2
2    3
3    4